services:

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    networks:
      - eb
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 30s
      retries: 5

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - eb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3010:80"
    networks:
      - eb
    depends_on:
      - postgres

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    networks:
      - eb
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "3012:3000"
    networks:
      - eb
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  prometheus:
    image: prom/prometheus
    ports:
      - "3013:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - eb
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    ports:
      - "3014:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - eb
    depends_on:
      - prometheus

volumes:
  pgdata:
  prometheus_data:

networks:
  eb:
